name: release

on:
  push:
    tags:
      - '*'

jobs:

  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Concatenate
      run: python ./build/concat.py release
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./h2unit.h
        asset_name: h2unit.h
        tag: ${{ github.ref }}

